### ISSUE TITLE
void printRegisters(void); error

### ISSUE THREAD

**Issue by gownojad** [LibreSolar/bq769x0-arduino-library#11]
sample code doesn't compile :(
Error is connected with :

#if BQ769X0_DEBUG
	void printRegisters(void);		
#endif

When I comment it, it compiles, but I need this for debuging of course.
I assume, that this is a simple problem, but I have not much experience with programming. Please help.

**Comment by martinjaeger** [comment]
Doese it help if you remove this comment?

https://github.com/LibreSolar/bq769x0-arduino-library/blob/fa81884e8ec0b9414c3f8f37749f90398c1b9686/bq769x0.h#L36

**Comment by gownojad** [comment]
thanks a lot, now it works!
