### ISSUE TITLE
CRC Implementation

### ISSUE THREAD

**Issue by tomeaton17** [LibreSolar/bq769x0-arduino-library#2]
Will this library be able to work with BQ769x0 devices which have CRC enabled at any point? If not if you could point me in the right direction I could have a go at implementing it myself.

**Comment by martinjaeger** [comment]
No, this one doesn't implement the CRC. Please have a look at the newer [mbed version of this library](https://github.com/LibreSolar/bq769x0_mbed_lib) which supports the CRC chips.

Please send a pull request if you update this library and enable the CRC. Thanks!

**Comment by tomeaton17** [comment]
@martinjaeger Thanks for the quick reply. Would the newer library work on an STM32? I have one lying around somewhere and could try it out. If not, I will try and update the Arduino code

**Comment by RianWardana** [comment]
Hi all, I have sent pull request #9 for implementing CRC and support for bq76940. Hope it helps, thanks!

**Comment by martinjaeger** [comment]
Thanks for the PR. Closing this issue now.
