### ISSUE TITLE
about 3cell with arduıno

### ISSUE THREAD

**Issue by yekta13** [LibreSolar/bq769x0-arduino-library#3]
your this project very  very great and ı will use in my graduate project.. so , thank you very much 

ı want to ask some queastions ;

ı will use arduıno and l  included cloumb countıng SOC  and OCV  from mbed to arduıno.     l use bq 76920 for 3 cells so what kind of settings l must make (for 3 cells ) in software and  arduıno sketch ?... 

and l  designed pcb in eagle like you but l use 1206 47ohm res for batteries res, but you used 2512 47ohm res. can it be problem?

best regards and so so thank you,

**Comment by martinjaeger** [comment]
Sorry, somehow missed to answer your questions. Hope they are resolved in the meantime.

Closing this issue now.

**Comment by yekta13** [comment]
I finished it... thanks for everything...

18 Eyl 2019 Çar 20:41 tarihinde Martin Jäger <notifications@github.com>
şunu yazdı:

**Comment by tsito04** [comment]
Hi y m trying to use bq 76920  how to use it pleas
