### ISSUE TITLE
Incorrect ADC Calculations

### ISSUE THREAD

**Issue by dHutchings** [LibreSolar/bq769x0-arduino-library#5]
FYI.  Please update line 623 of the .cpp file to be:

int16_t adcVal = 0; //has to explicitly be a 16bit signed int.

Merely calling out "int adcVal = 0;" is not enough.  According to the datasheet, the adc value must explicitly be a 16 bit value, otherwise the signed calculation will break.

The ADC current is signed (2's compliment), because the BQ chips can sense charging and discharging.

**Comment by dHutchings** [comment]
There is also a similar problem in the registers.h file.

lines 108 and 109 should be modified to:
"const uint8_t UV_delay_setting [4] = { 1, 4, 8, 16 };  // s
const uint8_t OV_delay_setting [4] = { 1, 2, 4, 8 };   // s"

using just "const int"s breaks the functionality of setCellUndervoltageProtection and setCellOvervoltageProtection.

**Comment by martinjaeger** [comment]
Thanks for providing this bug information. Can you send a pull request including the changes?

**Comment by dHutchings** [comment]
I tried.  I do not have permissions to push a new branch to github, which I will need to do to submit a PR.  Can you amend please?

**Comment by martinjaeger** [comment]
The workflow is as follows: 
- Fork the repository to your personal account.
- Push changes to your personal repository (the fork).
- Submit a pull request to merge your changes into the original repository.
