### ISSUE TITLE
   batCurrent calculation problem

### ISSUE THREAD

**Issue by lotusation** [LibreSolar/bq769x0-arduino-library#7]
Hi
I think here in updateCurrent function you should use shuntResistorValue_mOhm  insteade of 5.0
Am i right?

 if (ignoreCCReadyFlag == true || sys_stat.bits.CC_READY == 1)
  {
    adcVal = (readRegister(0x32) << 8) | readRegister(0x33);
    batCurrent = adcVal * 8.44 / 5.0;  // mA

**Comment by martinjaeger** [comment]
Yes, you are right and it is a mistake. Do you send a pull request with improvement?
